# See: http://jsontoyaml.com
---
  AWSTemplateFormatVersion: "2010-09-09"
  Parameters: 
    KeyName: 
      Description: "Name of an existing EC2 KeyPair to enable SSH access to the instance"
      Type: "String"
  Resources: 
    MyInstance: 
      Type: "AWS::EC2::Instance"
      Properties: 
        KeyName: 
          Ref: "KeyName"
        ImageId: "96761a90-635b-4718-8deb-f4ff57632db4"
        InstanceType: "m1.small"
        UserData: 
          Fn::Base64: "80"
  Outputs: 
    InstanceIp: 
      Value: 
        Fn::Join: 
          - ""
          - 
            - "ssh ec2-user@"
            - 
              Fn::GetAtt: 
                - "MyInstance"
                - "PublicIp"
      Description: "My ssh command"
